### ISSUE TITLE
make your first commit

### ISSUE THREAD

**Issue by stopmotio** [Redot-Engine/redot-engine#125]
### Tested versions

there are no versions yet

### System information

all of them

### Issue description

You are talking entirely too much shit to have exactly zero commits. At the very least implement the PRs you have doing most of the work for you. Most importantly you need to differentiate yourself from Godot in some form other than having an even more annoying Twitter account than them.

Also they got way more donors than they lost from that tweet, so it was a net profit. lol

### Steps to reproduce

—

### Minimal reproduction project (MRP)

—

**Comment by Bioblaze** [comment]
Please stop being rude, its been less then 3 days. And your foaming at the mouth.

Seriously, find something todo with your time.

**Comment by rayzorite** [comment]
this mf has no Job 💀..
Jobless ahh

**Comment by stopmotio** [comment]
> Please stop being rude, its been less then 3 days. And your foaming at the mouth.
> 
> Seriously, find something todo with your time. 

Three days should get you more than started. I can provide you with a pull request if you want.

**Comment by stopmotio** [comment]
Tomorrow I'll go ahead and submit a PR to show you all that I mean business. Trying to help but I can be mean at times lol
