### ISSUE TITLE
Anyone who associates with this "project" is mentally deficient

### ISSUE THREAD

**Issue by tonogram** [Redot-Engine/redot-engine#15]
### Tested versions

Reproducible in all versions.

### System information

Noticable to anyone that can read.

### Issue description

Title is self-explanatory.

### Steps to reproduce

If you ingest enough lead paint then you'll be on the same page as these guys.

### Minimal reproduction project (MRP)

Not necessary.

**Comment by danbudworthmead** [comment]
classic right wingers, stealing a commie developed project and trying to captialise on feigned outrage

**Comment by FireBrandMint** [comment]
Behold, trolling.
...
It was better in the old days...

**Comment by Captain-Wet-Beard** [comment]
![OIP (1)](https://github.com/user-attachments/assets/5f900156-91a3-4c2d-83e5-82a8d3aad377)

**Comment by Captain-Wet-Beard** [comment]
> classic right wingers, stealing a commie developed project and trying to captialise on feigned outrage

You can't steal a FOSS project, nobody owns it lel

**Comment by codesatpm** [comment]
you just associated yourself by opening a issue.

**Comment by tonogram** [comment]
standing outside with a protest sign does not make one an associate. so concerned with owning me on the internet that you cannot spare a moment to think about whether or not your sick comeback makes any sense.

**Comment by Salvakiya** [comment]
Closing as this is not productive and is helping no one.

**Comment by Nicholai-Korea** [comment]
This will be getting deleted as soon as Drew our lead dev on this gives permissions to the other Devs so just give us some time folks.

**Comment by tonogram** [comment]
Speaking of not being productive and helping no one...

**Comment by Captain-Wet-Beard** [comment]
> This will be getting deleted as soon as Drew our lead dev on this gives permissions to the other Devs so just give us some time folks.

I doubt anyone really cares much tbh, its just a shitpost by a Rust dev stereotype.

**Comment by lambdadeltakay** [comment]
Creating a fork of a engine because of inane culture war shit has to be the funniest shit imaginable

**Comment by Salvakiya** [comment]
> Creating a fork of a engine because of inane culture war shit has to be the funniest shit imaginable

this influenced it but there have been a few people wanting to for godot for years. In fact there are many forks of Godot.

locking thread
