### ISSUE TITLE
Too woke

### ISSUE THREAD

**Issue by lvxnull** [Redot-Engine/redot-engine#184]
### Tested versions

they're all woke

### System information

i hate woke

### Issue description

This project is too woke

### Steps to reproduce

- Make a PR that removes woke
- It gets closed (not woke enough)

### Minimal reproduction project (MRP)

see #174

**Comment by Alxira5** [comment]
The code is not really 'woke' and the code is not subject to politics, and the only thing that is woke is the Godot Foundation and its toxic community.

ReDot Engine is not subject to political issues and only seeks to focus on its development, and that is the reason for its existence.

**Comment by lvxnull** [comment]
coding is woke people hobby, real men hunt animal and shoot gun

**Comment by mrjustaguy** [comment]
Godot Foundation isn't Woke. there are employees at the foundation that are Woke. That's a fairly big difference. This isn't a huge surprise to anyone that read Godot's Code of Conduct (which I have loong before any of this happened) that is against discrimination based on political ideals, which Wokeness is, among other things.

Second, just because there are some Toxic members of a community, doesn't mean the whole Community is toxic.

Third, Redot is plagued by political issues as it's whole existence is in essence a Political response.

**Comment by warcaninos** [comment]
> The code is not really 'woke' and the code is not subject to politics, and the only thing that is woke is the Godot Foundation and its toxic community.
> 
> ReDot Engine is not subject to political issues and only seeks to focus on its development, and that is the reason for its existence.

Next time don't reply and report the account, they feed on your attention.

**Comment by lvxnull** [comment]
true im a literal vampire btw

**Comment by ALH477** [comment]
This is retarded

**Comment by Alxira5** [comment]
> > The code is not really 'woke' and the code is not subject to politics, and the only thing that is woke is the Godot Foundation and its toxic community.
> > ReDot Engine is not subject to political issues and only seeks to focus on its development, and that is the reason for its existence.
> 
> Next time don't reply and report the account, they feed on your attention.

The best thing would be to close the Issues of this style and not waste time on this, and I can assure you that they are trolls who have never touched a line of code in their lives.

This is just unfortunate and I have no other word to describe it.

**Comment by 13Character5** [comment]
Please say you're a troll

**Comment by meltland** [comment]
hrrrghh!! Woke!!!!!! :rage: :rage:

**Comment by ALH477** [comment]
> hrrrghh!! Woke!!!!!! :rage: :rage: 

Go back to discord chubs chubs

**Comment by RakibRyan** [comment]
> coding is woke people hobby, real men hunt animal and shoot gun

Please get a job.
