### ISSUE TITLE
unban me from your discord OwO

### ISSUE THREAD

**Issue by meltland** [Redot-Engine/redot-engine#186]
### Tested versions

4.3.dev.onikaburger

### System information

onikaOS

### Issue description

unban `eastagon64` :3

### Steps to reproduce

\> be onika burger truther
\> get wrongfully banned for spreading the word of onika burger
\> scream "no"
\> fall to knees
\> beg for forgiveness from daddy redot

**Comment by ALH477** [comment]
Get a life.

**Comment by StellaLovesTech** [comment]
> Get a life.

![image](https://github.com/user-attachments/assets/230b743a-3ab9-4bed-8224-9c8f1e4f908f)

**Comment by RakibRyan** [comment]
> ### Tested versions
> 
> 4.3.dev.onikaburger
> ### System information
> 
> onikaOS
> ### Issue description
> 
> unban `eastagon64` :3
> ### Steps to reproduce
> 
> > be onika burger truther > get wrongfully banned for spreading the word of onika burger > scream "no" > fall to knees > beg for forgiveness from daddy redot
> ### Minimal reproduction project (MRP)
> 
> ![image](https://private-user-images.githubusercontent.com/162374746/373910301-60a1536e-0191-4034-8877-eca2c6ad9f16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODEzNjAsIm5iZiI6MTcyODE4MTA2MCwicGF0aCI6Ii8xNjIzNzQ3NDYvMzczOTEwMzAxLTYwYTE1MzZlLTAxOTEtNDAzNC04ODc3LWVjYTJjNmFkOWYxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwMjE3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTlkMDhkODU1YTU0ZWEzYTU5ODBkZmEyODA4NDM2OGI4ODhhM2NiMjJlNTBiMGNmNGRiOWE3OTU5YmM0NDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d1YF74XWbVAN1eU3a-clkC3Od7uVVRHwAW6HLb3E8mo)

Get a job. Please get a job

**Comment by meltland** [comment]
> > ### Tested versions
> > 4.3.dev.onikaburger
> > ### System information
> > onikaOS
> > ### Issue description
> > unban `eastagon64` :3
> > ### Steps to reproduce
> > > be onika burger truther > get wrongfully banned for spreading the word of onika burger > scream "no" > fall to knees > beg for forgiveness from daddy redot
> > 
> > 
> > ### Minimal reproduction project (MRP)
> > ![image](https://private-user-images.githubusercontent.com/162374746/373910301-60a1536e-0191-4034-8877-eca2c6ad9f16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODEzNjAsIm5iZiI6MTcyODE4MTA2MCwicGF0aCI6Ii8xNjIzNzQ3NDYvMzczOTEwMzAxLTYwYTE1MzZlLTAxOTEtNDAzNC04ODc3LWVjYTJjNmFkOWYxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwMjE3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTlkMDhkODU1YTU0ZWEzYTU5ODBkZmEyODA4NDM2OGI4ODhhM2NiMjJlNTBiMGNmNGRiOWE3OTU5YmM0NDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d1YF74XWbVAN1eU3a-clkC3Od7uVVRHwAW6HLb3E8mo)
> 
> Get a job. Please get a job

I was looking for a job, and then I found a job
And heaven knows I'm miserable now
