### ISSUE TITLE
I have a issue

### ISSUE THREAD

**Issue by lambdadeltakay** [Redot-Engine/redot-engine#19]
### Tested versions

None

### System information

msdos

### Issue description

![20240922_122256](https://github.com/user-attachments/assets/f4e5f373-b6fd-49f8-b682-7877d226643c)

### Steps to reproduce

.

### Minimal reproduction project (MRP)

.

**Comment by JohnnyThunder2** [comment]
This doesn't look like a legitimate issue.

**Comment by ItsAlphaNeon** [comment]
> ### Tested versions
> 
> None
> ### System information
> 
> msdos
> ### Issue description
> 
> ![20240922_122256](https://private-user-images.githubusercontent.com/144762384/372271780-f4e5f373-b6fd-49f8-b682-7877d226643c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3Mzc1NzQsIm5iZiI6MTcyNzczNzI3NCwicGF0aCI6Ii8xNDQ3NjIzODQvMzcyMjcxNzgwLWY0ZTVmMzczLWI2ZmQtNDlmOC1iNjgyLTc4NzdkMjI2NjQzYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQyMzAxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWJkMDE4NjVlNzgwYzNjMjAzMmUxN2UxNDZjOWIxOTQ3Nzg4Y2Y5OTc3NGJjYjlhNWEwNmVlYWMzYjM1MDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CJCHIhW0jfKfgErlKi3uzyAAQT_Sl2P5zEGgEMsLuBg)
> ### Steps to reproduce
> 
> .
> ### Minimal reproduction project (MRP)
> 
> .

🤡

**Comment by lambdadeltakay** [comment]
> This doesn't look like a legitimate issue.

Prove it

**Comment by ItsAlphaNeon** [comment]
> ### Tested versions
> 
> None
> ### System information
> 
> msdos
> ### Issue description
> 
> ### Steps to reproduce
> 
> .
> ### Minimal reproduction project (MRP)
> 
> .

🤡🤡🤡

**Comment by FireBrandMint** [comment]
Another humiliation fetishist?

**Comment by lambdadeltakay** [comment]
> > ### Tested versions
> > 
> > None
> > ### System information
> > 
> > msdos
> > ### Issue description
> > 
> > ### Steps to reproduce
> > 
> > .
> > ### Minimal reproduction project (MRP)
> > 
> > .
> 
> 🤡🤡🤡

That's not a relevant comment

**Comment by SeanRamey** [comment]
Don't give the child attention. That's all he wants. Let him go mope in the corner.

**Comment by lambdadeltakay** [comment]
> Don't give the child attention. That's all he wants. Let him go mope in the corner.

Isn't this entire fork revolving around throwing a fit

**Comment by FringeSci-com** [comment]
This isn't a political project. This was started because there's features that aren't being implemented in the actual engine. Just because there's drama going on doesn't mean that this is a political project.

Also just because someone on twitter gives this a shout out doesn't mean that they has anything to do with the engine. If you're butthurt about people on twitter, yell at them, not random github projects.

**Comment by WanderLanz** [comment]
Using github features to make disruptive content is against the [GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service) and [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines). Please see the [Github Acceptable Use Policicies](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#2-user-safety) to learn more.

This comment was made by a private fork of the GitHub ToS bot, please make an issue at https://github.com/WanderLanz/TosBot if you believe this is a mistake.
