### ISSUE TITLE
Monosodium glutamate

### ISSUE THREAD

**Issue by meltland** [Redot-Engine/redot-engine#202]
Monosodium glutamate (MSG), also known as sodium glutamate, is a [sodium](https://en.wikipedia.org/wiki/Sodium) [salt](https://en.wikipedia.org/wiki/Salt_(chemistry)) of [glutamic acid](https://en.wikipedia.org/wiki/Glutamic_acid). MSG is found naturally in some foods including [tomatoes](https://en.wikipedia.org/wiki/Tomato) and [cheese](https://en.wikipedia.org/wiki/Cheese) in this glutamic acid form.[[2]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-FDA-2)[[3]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-HealthCanada-3)[[4]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-Agostoni_2000-4) MSG is used in cooking as a flavor enhancer with a savory taste that intensifies the meaty, savory flavor of food, as naturally occurring glutamate does in foods such as [stews](https://en.wikipedia.org/wiki/Stew) and meat soups.[[5]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-Ikeda-5)[[6]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-OMG_I_love_MSG-6)

MSG was first prepared in 1908 by Japanese [biochemist](https://en.wikipedia.org/wiki/Biochemist) [Kikunae Ikeda](https://en.wikipedia.org/wiki/Kikunae_Ikeda), who tried to isolate and duplicate the savory taste of [kombu](https://en.wikipedia.org/wiki/Kombu), an edible [seaweed](https://en.wikipedia.org/wiki/Seaweed) used as a [broth](https://en.wikipedia.org/wiki/Broth) (dashi) for [Japanese cuisine](https://en.wikipedia.org/wiki/Japanese_cuisine). MSG balances, blends, and rounds the perception of other tastes.[[7]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-Loliger-7)[[8]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-Yamaguchi91-8) MSG, along with [disodium ribonucleotides](https://en.wikipedia.org/wiki/Disodium_ribonucleotides), is commonly used and found in [stock (bouillon) cubes](https://en.wikipedia.org/wiki/Stock_cube), [soups](https://en.wikipedia.org/wiki/Soup), [ramen](https://en.wikipedia.org/wiki/Ramen), [gravy](https://en.wikipedia.org/wiki/Gravy), [stews](https://en.wikipedia.org/wiki/Stew), [condiments](https://en.wikipedia.org/wiki/Condiment), savory [snacks](https://en.wikipedia.org/wiki/Snack), etc.

The U.S. [Food and Drug Administration](https://en.wikipedia.org/wiki/Food_and_Drug_Administration) has given MSG its [generally recognized as safe](https://en.wikipedia.org/wiki/Generally_recognized_as_safe) (GRAS) designation.[[9]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-FDAQnA-9) It is a popular misconception that MSG can cause [headaches](https://en.wikipedia.org/wiki/Headaches) and other feelings of discomfort, known as "[Chinese restaurant syndrome](https://en.wikipedia.org/wiki/Chinese_restaurant_syndrome)". Several [blinded studies](https://en.wikipedia.org/wiki/Blinded_study) show no such effects when MSG is combined with food in normal concentrations, and are inconclusive when MSG is added to broth in large concentrations.[[9]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-FDAQnA-9)[[10]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-Ob2016-10)[[11]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-11) The [European Union](https://en.wikipedia.org/wiki/European_Union) classifies it as a [food additive](https://en.wikipedia.org/wiki/Food_additive) permitted in certain foods and subject to quantitative limits. MSG has the [HS code](https://en.wikipedia.org/wiki/HS_code) 29224220 and the [E number](https://en.wikipedia.org/wiki/E_number) E621.[[12]](https://en.wikipedia.org/wiki/Monosodium_glutamate#cite_note-UKGovEnumbr-12)

**Comment by StellaLovesTech** [comment]
I agree with this!

**Comment by StellaLovesTech** [comment]
> Maintainer, block this person please

What? But that's not allowed that is too woke for this project.

**Comment by meltland** [comment]
> Maintainer, block this person please

oh, moderators! :point_up:

**Comment by StellaLovesTech** [comment]
> Maintainer, block this person please

Sir, have you heard about out lord and savior the bee movie?
