### ISSUE TITLE
HELP! WOKE VIRUS IN KOMnbIOTEP Ë氺NKA!!!

### ISSUE THREAD

**Issue by BasedVideoGamer** [Redot-Engine/redot-engine#208]
### Tested versions

Reproducible in: any version

### System information

Windows 9 - Redot v4.0.3.stable - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 11 (nvidia, 510.85.02) - AMD Core i6-9KF CPU @ 2.28GHz

### Issue description

![dirOpened output of login](https://github.com/user-attachments/assets/ba4c8276-d69e-4446-8ae7-cf8d2e4ea226)
HELP!!! POMAGİTYE YA NE ZNAU SHTO S ETЇM DELAT!!!

### Steps to reproduce

YA PORTIROVAL IGRU PO SMESHARIKAM NA REDOT I MOY KOMP ZARAZILSA WOKE VIRUSOM

### Minimal reproduction project (MRP)

.

**Comment by vktf1** [comment]
![image](https://github.com/user-attachments/assets/8970fb3a-bddd-41a0-97a9-000e77314015)

**Comment by loadstring1** [comment]
> o kurwa tylko nie woke virus😱😱😱😱

w ogóle ktoś zauważył że on ma windowsa 9?

skąd on ma windowsa 9 od kiedy tak można?
