### ISSUE TITLE
im skibiding my toilet

### ISSUE THREAD

**Issue by meltland** [Redot-Engine/redot-engine#209]
![image](https://github.com/user-attachments/assets/89cf62bd-2260-4dc6-b195-fe0227b62639)
![image](https://github.com/user-attachments/assets/ed4de506-c430-4ca0-8b2e-62771547f645)

**Comment by Nicholai-Korea** [comment]
Closed

**Comment by vktf1** [comment]
![image](https://github.com/user-attachments/assets/8970fb3a-bddd-41a0-97a9-000e77314015)

**Comment by vktf1** [comment]
where are my meds
