### ISSUE TITLE
i dont use my github account for anything important but okay

### ISSUE THREAD

**Issue by meltland** [Redot-Engine/redot-engine#210]
![image](https://github.com/user-attachments/assets/e19fbc32-d8d2-492a-85c4-4563affe8877)

**Comment by meltland** [comment]
![image](https://github.com/user-attachments/assets/33a8cb76-0bc1-4343-9358-935ba2dd2b10)
okay im not sure if thats really what happened

**Comment by meltland** [comment]
![image](https://github.com/user-attachments/assets/38eaf8dc-52c6-44df-98fd-e1dfc9441347)
thats hilarious keep pursuing your comedy career youre going places

**Comment by StellaLovesTech** [comment]
Stop NOW! This isnt funny. The godot woke mob is coming for us!

**Comment by meltland** [comment]
![image](https://github.com/user-attachments/assets/b494d612-5f32-43ab-bdd3-b64aec6c35d2)
i do both at once its called multitasking

**Comment by StellaLovesTech** [comment]
Speaking of, when will they delete the woke(communist) open source license?

**Comment by meltland** [comment]
![image](https://github.com/user-attachments/assets/dec6e29f-d09c-4c0f-9a54-c4755ac5b170)
im just a hater :3

**Comment by StellaLovesTech** [comment]
![image](https://github.com/user-attachments/assets/e7d225ea-8a96-4777-8d1a-2e5aad9451bf)
all these vms have alt accounts logged in the redot server btw

**Comment by StellaLovesTech** [comment]
May I mention I actually use arch linux, BTW?

**Comment by loadstring1** [comment]
> May I mention I actually use arch linux, BTW?

dang bro im used to windows stuff i tried switching to linux mint, ubuntu but i just can't cuz i prefer the way bloaty windows is 😭

**Comment by StellaLovesTech** [comment]
> > May I mention I actually use arch linux, BTW?
> 
> dang bro im used to windows stuff i tried switching to linux mint and ubuntu but i just can't cuz i prefer the way bloaty windows is 😭 (also skill issue for me cuz i have nvidia graphics card so it works way better on windows than linux)



I'd just like to interject for a moment. What you're refering to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.

Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called Linux, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.

There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions of GNU/Linux!

**Comment by loadstring1** [comment]
> > > May I mention I actually use arch linux, BTW?
> > 
> > 
> > dang bro im used to windows stuff i tried switching to linux mint and ubuntu but i just can't cuz i prefer the way bloaty windows is 😭 (also skill issue for me cuz i have nvidia graphics card so it works way better on windows than linux)
> 
> I'd just like to interject for a moment. What you're refering to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.
> 
> Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called Linux, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.
> 
> There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions of GNU/Linux!

there i edited my comment now its GNU/linux

better now?
