### ISSUE TITLE
[Discussion] I'm really hoping to see some progress soon! Is anyone else getting worried?

### ISSUE THREAD

**Issue by AntiWokeSoldier** [Redot-Engine/redot-engine#216]
### Tested versions

We CAN do it! Don't listen to what the wokies are saying on twitter! Godspeed Devs!

### System information

Windows 10

### Issue description

![95q42i](https://github.com/user-attachments/assets/3b0cbe63-ce07-461d-a616-d11fbdc68421)

### Steps to reproduce

Thoughts?

### Minimal reproduction project (MRP)

we will win against the woke mob!

**Comment by RakibRyan** [comment]
You know what's funny? Some low iq genius had to do a google search to find an image which means they saw multiple 💩 images. Nice way to say to the world only shit lover is you and your low iq. You probably Don't even know what iq is.

**Comment by AntiWokeSoldier** [comment]
> You know what's funny? Some low iq genius had to do a google search to find an image which means they saw multiple 💩 images. Nice way to say to the world only shit lover is you and your low iq. You probably Don't even know what iq is.

![tumblr_nlzxoz2m9c1trlgoso1_500](https://github.com/user-attachments/assets/b82d2695-52f6-473c-81e5-b18719b1de14)
