### ISSUE TITLE
Do you think we could get Elon Musk to endorse or talk about Redot?

### ISSUE THREAD

**Issue by AntiWokeSoldier** [Redot-Engine/redot-engine#217]
### Tested versions

Just imagine if we launched an NFT and got Elon to endorse it... we would be the future of game development!

### System information

Windows

### Issue description

![95trvy](https://github.com/user-attachments/assets/d37cebef-e652-49ab-ae69-98b8e38cd70d)
I was thinking we could name our NFT $ShitCoin!!!

### Steps to reproduce

![95q54v](https://github.com/user-attachments/assets/6f392360-d120-445d-9bee-920c2a149db7)

### Minimal reproduction project (MRP)

Thoughts!??!!

**Comment by TheHyper-Dev** [comment]
I found your ip

**Comment by RakibRyan** [comment]
You know what's funny? Some low iq genius had to do a google search to find an image which means they saw multiple :poop: images. Nice way to say to the world only shit lover is you and your low iq. You probably Don't even know what iq is.

**Comment by AntiWokeSoldier** [comment]
> You know what's funny? Some low iq genius had to do a google search to find an image which means they saw multiple 💩 images. Nice way to say to the world only shit lover is you and your low iq. You probably Don't even know what iq is.

![tumblr_nlzxoz2m9c1trlgoso1_500](https://github.com/user-attachments/assets/15556722-633e-4c3f-8c96-d8bcc27e695e)

**Comment by AntiWokeSoldier** [comment]
> I found your ip

![halt2racohu51](https://github.com/user-attachments/assets/dce7a1dc-ada6-4e47-a09a-b264eb1f9c43)

**Comment by AntiWokeSoldier** [comment]
> I found your ip

![Untitled](https://github.com/user-attachments/assets/ef68274b-39bb-408c-98f1-e496527dfaee)
