### ISSUE TITLE
https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization#blocking-a-user-in-a-comment

### ISSUE THREAD

**Issue by meltland** [Redot-Engine/redot-engine#233]
### Tested versions

https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization#blocking-a-user-in-a-comment

### System information

https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization#blocking-a-user-in-a-comment

### Issue description

https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization#blocking-a-user-in-a-comment

### Steps to reproduce

https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization#blocking-a-user-in-a-comment

### Minimal reproduction project (MRP)

https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization#blocking-a-user-in-a-comment

**Comment by Starkium** [comment]
working on it, I don't know if I have those perms yet

**Comment by jlitewski** [comment]
Reported the user to Github for this spam. Getting tired of these trolls
