### ISSUE TITLE
someone here can delete issues so delete these ones

### ISSUE THREAD

**Issue by meltland** [Redot-Engine/redot-engine#237]
#218 #217 #216 delete these jesus christ

**Comment by JohnnyThunder2** [comment]
Yeah, seems their raiding us... really gotta wonder who these people are that wanna abuse Github because they don't have a life. Seriously, people, move on with your lives... go make things...

This is a place where we focus on coding and engineering, politics is for Twitter please.

**Comment by stonerl** [comment]
Also report these users to GitHub so their accounts get removed.
