### ISSUE TITLE
Noticeable lack of Skibidi Toilet

### ISSUE THREAD

**Issue by ahxgamma** [Redot-Engine/redot-engine#26]
### Tested versions

Always present

### System information

N/A

### Issue description

**Description:**

It has come to our attention that the Redot Engine currently lacks any integration or support for the infamous **Skibidi Toilet** phenomenon, which has become a cultural icon in the gaming community. The absence of this whimsical element is not only surprising but also limits the engine's potential for humor and creativity in game development.

**Expected Behavior:**

The Redot Engine should provide assets, examples, or documentation on how to incorporate the Skibidi Toilet meme into games. This could include:
- **3D models** of the Skibidi Toilet.
- **Animations** that capture its iconic dance.
- **Audio effects** or sound bites that are recognizable to fans of the meme.

**Actual Behavior:**

Currently, there are no resources, examples, or references related to the Skibidi Toilet in the Redot Engine, making it difficult for developers to leverage this popular culture reference in their projects.

**Proposed Solution:**

- Create and provide official Skibidi Toilet assets within the Redot Engine's asset library.
- Develop tutorials or documentation that guide users on how to integrate Skibidi Toilet elements into their games effectively.

**Additional Notes:**

Incorporating this meme could greatly enhance the engine's appeal and engagement within the developer community, allowing for more creative and humorous game designs. It would also position Redot as a more fun and relatable option for game developers looking to tap into current trends.

**Priority:** Medium

### Steps to reproduce

Open Godot, and be disappointed by the lack of rizz.

### Minimal reproduction project (MRP)

N/A

**Comment by Salvakiya** [comment]
Spam
