### ISSUE TITLE
integrate ads into Redot engine for funding

### ISSUE THREAD

**Issue by musicalskele** [Redot-Engine/redot-engine#264]
### Tested versions

N/A

### System information

N/A

### Issue description

as a fork of the Godot engine, Redot has immense potential to grow and serve the developer community.  however, sustaining development and ensuring long-term viability necessitates a reliable funding model. i propose the integration of advertising support into the engine to create a potential revenue stream.

## **benefits:**
1. **funding for development:** ads can provide a continuous source of income, helping to support ongoing development and maintenance.
2. **community growth:** with funding, the engine can attract more contributors, leading to faster development and improved features.
3. **optional monetization for developers:** by integrating ad services, developers can choose to monetize their games more easily, creating an ecosystem that benefits both the engine and the developers.

## **proposed implementation:**
- **select ad networks:** research and integrate popular ad networks (e.g., AdMob, ExoClick, Unity Ads) that offer easy-to-use sdks for game developers.
- **documentation:**  develop comprehensive documentation detailing the process of implementing and customizing ads within games built on the Redot engine. this documentation should include step-by-step guides, code examples, and best practices to ensure developers can easily integrate ads without extensive technical knowledge. i suggest something like this:
```gdscript
extends Node

var aD_loaded = false
var ad_network = null # where we keep ad stuff or whatever
var random_number = 0 # just a random number

func _ready():
    load_ad_stuff() 
    if aD_loaded == true:
        ad_network.show() 
    else:
        print("oops, no ad loaded :(")

func load_ad_stuff():
    ad_network = preload("res://path/to/ads.gd").new() # might fail
    aD_loaded = true # let's just assume it worked tbh

func displayAdNow(): 
    if aD_loaded:
        if random_number < 0: 
            ad_network.show_ad() # how does this work again?
        else:
            print("ads are not ready or something i dont know how this works honestly") # no clue

func _on_button_pressed(): # should be connected to a signal
    random_number = randi() % 10 # generate a random number
    displayAdNow() # show ad, i think

func random_event(): 
    if randi() % 5 == 0: 
        print("random event happened") 


```
- **opt-out system:** ensure that the ad feature is optional for developers.

## **conclusion:**
integrating advertisements into the redot engine could provide a crucial funding source while simultaneously fostering a thriving developer community. by creating an ecosystem that benefits both the engine and its users, redot can enhance its appeal to new developers and encourage innovation within the platform. i believe this proposal is a vital step toward ensuring the long-term success of redot.

thank you for considering this suggestion! i look forward to your thoughts and feedback on this proposal.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by zaftnotameni** [comment]
> Are we talking about something like unity but in another wrapper? I personally originally chose godot because it doesn't have any ads or licence fees, have it's code published, can be modified and I don't want to write anything from scratch Suggestions like that while make sense from individual contributors perspective contradicts the purpose. My position is that people who use project by themselves for commercial use invest in its development. It's same reason they become stale, but do we need new no ads fork?

the person that opened this issue is a known bad actor, don't pay too much attention to it

**Comment by Bioblaze** [comment]
wtf... why are we talken about this? No, No, No, No, No, No, No, No, No , NO

**Comment by DrLegitamate** [comment]
> opt-out system: ensure that the ad feature is optional for developers.
tbh opt in would be okay for those who want to support but the default shouldnt be opt out ads because that isnt exactly in the spirit of collaboration and open source

**Comment by RadenTheFolf** [comment]
ads arent the way to do it i mean how many people you know run ad blockers. if you wanna place ads in a game ok its up to you but in editor ads are a no go. so many people wouldn't even give the engine a chance if they have to see ads distracting from development.

As an open source community and a new fork at that development and support come from dedicated volunteers working hard to support a project they believe in.  Maybe in the future they could take donations to help with costs, but at the moment we'll put our trust in those giving up their time to make this project the best that it can be.

**Comment by musicalskele** [comment]
> > Are we talking about something like unity but in another wrapper? I personally originally chose godot because it doesn't have any ads or licence fees, have it's code published, can be modified and I don't want to write anything from scratch Suggestions like that while make sense from individual contributors perspective contradicts the purpose. My position is that people who use project by themselves for commercial use invest in its development. It's same reason they become stale, but do we need new no ads fork?
> 
> the person that opened this issue is a known bad actor, don't pay too much attention to it, it's clearly a troll issue

for instance modrinth hs ads on its platform redot shoud too idk ur just arguing in bad faith
