### ISSUE TITLE
Copyright Usage and Reference Hunting

### ISSUE THREAD

**Issue by Starkium** [Redot-Engine/redot-engine#270]
### Tested versions

N/A

### System information

N/A

### Issue description

We're in the process of renaming portions of the Godot code base to Redot. We have to be very careful about not changing copyright. Some stuff has been done by hand while other stuff we've tried to iterate a bit faster over. There is potential for some hiccups.

We're pinning this topic here so that anyone can report any places that seem be incorrectly changed. You may also report here places that haven't been changed yet that need to be changed.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by MrDraxs** [comment]
README.md and logo_outline.svg needs to be changed ASAP
![image](https://github.com/user-attachments/assets/97f33529-4cf4-47d1-8508-5df403a0e972)

**Comment by SkogiB** [comment]
When importing old version projects, the version warning dialogue lists the prior version as Redot 3.x/4.x instead of the fact that it was actually a Godot project. It's a minor issue compared to others, and will require some extra work to detect Godot vs Redot projects, but it may be important in the future when Redot is more different and users will need to be warned clearly that moving a project from Godot to Redot might have unique concerns by then.

![image](https://github.com/user-attachments/assets/a72d8605-1a3c-41dd-b950-caca53e5db27)

**Comment by decryptedchaos** [comment]
>When importing old version projects, the version warning dialogue lists the prior version as Redot 3.x/4.x instead of the fact that it was actually a Godot project.

There isn't really a way to differentiate between a Godot/Redot project at the present time, you get this message simply because your project was last edited in 4.0 version of the engine (branding notwithstanding)  

Its always advisable to make a copy of your project when you are trying to convert it to a new version, as it will make changes to your project.

**Comment by SkogiB** [comment]
Issue Report page needs to be rebranded

![image](https://github.com/user-attachments/assets/7d8676bd-e372-483b-9d46-a63d94397a07)

**Comment by Starkium** [comment]
> README.md and logo_outline.svg needs to be changed ASAP ![image](https://private-user-images.githubusercontent.com/67723468/374631246-97f33529-4cf4-47d1-8508-5df403a0e972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzAyNjAsIm5iZiI6MTcyODQyOTk2MCwicGF0aCI6Ii82NzcyMzQ2OC8zNzQ2MzEyNDYtOTdmMzM1MjktNGNmNC00N2QxLTg1MDgtNWRmNDAzYTBlOTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIzMjYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMWVmNGQxZGUyMGEzOGZiZjM0YTcyZDQ0MmYxMGUyNmU3YmFmZWUyNDNmYzU3NThhNDgzMGY1MGQzYmQ2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.slCPKN5dgRfc53TsiBlW_mKlx4dFWDAslkX_NoCyi7Y)

We're planning to change it substantially instead of just rebrand. Perhaps an intermediate step is ok.

**Comment by apofex** [comment]
> > README.md and logo_outline.svg needs to be changed ASAP ![image](https://private-user-images.githubusercontent.com/67723468/374631246-97f33529-4cf4-47d1-8508-5df403a0e972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzAyNjAsIm5iZiI6MTcyODQyOTk2MCwicGF0aCI6Ii82NzcyMzQ2OC8zNzQ2MzEyNDYtOTdmMzM1MjktNGNmNC00N2QxLTg1MDgtNWRmNDAzYTBlOTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIzMjYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMWVmNGQxZGUyMGEzOGZiZjM0YTcyZDQ0MmYxMGUyNmU3YmFmZWUyNDNmYzU3NThhNDgzMGY1MGQzYmQ2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.slCPKN5dgRfc53TsiBlW_mKlx4dFWDAslkX_NoCyi7Y)
> 
> We're planning to change it substantially instead of just rebrand. Perhaps an intermediate step is ok.

#164 Will it be good?

**Comment by kabachuha** [comment]
The most important thing for any fork is to update the LICENSE.md file and add the new copyright on top of the existing ones

https://github.com/Redot-Engine/redot-engine/blob/b52811b83478bd06c5bcf39a93bbf53dd03cc9bf/LICENSE.txt#L1-L4

This way the original project will not own the new changes, including all the branding changes and will have to include the reverse mention if they'll need to grab the forked code parts

**Comment by tokengamedev** [comment]
`Version.py` needs to be updated, specifically line 351 and line 1387. It is causing improper visual studio project.

There are other properties being set, it can be changed later

**Comment by SkogiB** [comment]
> `Version.py` needs to be updated, specifically line 351 and line 1387. It is causing improper visual studio project.
> 
> There are other properties being set, it can be changed later

We have a PR aimed at master that can go in once we've decided on a better branch organization here, I took a look at it earlier while reviewing all the PRs stacked up on readme changes that are outdated now

https://github.com/Redot-Engine/redot-engine/pull/63

**Comment by tokengamedev** [comment]
> Version.py needs to be updated, specifically line 351 and line 1387. It is causing improper visual studio project.

will be fixed by the PR https://github.com/Redot-Engine/redot-engine/pull/664

**Comment by Spartan322** [comment]
Is this still relevant?

**Comment by RadenTheFolf** [comment]
This issue is now a subset of #692 and #705. Please defer all comments on changes for rebranding and copyrights to the version of the engine they apply to.
