### ISSUE TITLE
[CAUTION] Woke suggestions from Redot community 

### ISSUE THREAD

**Issue by Renjiro-kun** [Redot-Engine/redot-engine#41]
### Tested versions

no version tested becaue i dont want to support wokedot

### System information

Arch 7.0

### Issue description

There are no available builds for prototyping my new game. The only workaround to do it - download stable wokedot release, which is unacceptable since I don`t want to support DEI backed engine. Because no one sees any issue with this, current fork should be labeled as woke-friendly engine.

### Steps to reproduce

Open Redot-engine issue #39
![image](https://github.com/user-attachments/assets/f08072ad-9f4e-4898-ae56-d936f92308fb)

### Minimal reproduction project (MRP)

Unfortunately woke

**Comment by LinuxWizzerd** [comment]
Can you please make an actual issue instead of something that has nothing to do with the functionality of the program
Godot has plenty of problems you can look up

**Comment by Renjiro-kun** [comment]
It`s an actual issue because I can`t make my game. What am I supposed to do at this point????

**Comment by VaidenKelsier** [comment]
> It's an actual issue because I can't make my game. What am I supposed to do at this point????

Get over it?

**Comment by Salvakiya** [comment]
spam, useless issue
