### ISSUE TITLE
When making Redot community forum, avoid Discourse.

### ISSUE THREAD

**Issue by darkhog** [Redot-Engine/redot-engine#42]
### Tested versions

N/A

### System information

N/A

### Issue description

Discourse is made by the woke crowd, on top of being a really terrible forum system that requires JS to function (making it slow and potentially insecure if a bug in JS interpreter gets discovered). Instead, a more classic forum would be a better choice, such as SMF or phpBB.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by Salvakiya** [comment]
Not related to Redot engine development
