### ISSUE TITLE
[suggestion] Proposal to improve the redot-engine's git repository

### ISSUE THREAD

**Issue by 73NN0** [Redot-Engine/redot-engine#426]
### Tested versions

N/A

### System information

linux/window/darwin

### Issue description

Hello,

I'm Obiwor, I've been following the Godot project for a while and I've never dared to take the first step towards any kind of improvement proposal.  To tell you a bit more about myself, I'm a JS dev and I used to work on a web project at Airbus where I trained all my colleagues on Git (senior and junior alike) over the past 3 years.

However, since I've noticed a clear desire on the part of Redot to distinguish itself from Godot, I've dared, and I'd like to suggest that you review how you manage your Git project.

At the moment, it's very difficult to find your way around the branches and easily see what improvements have been made. So I imagine that it's unthinkable to go back to the way things were, because undoing a merge commit is much more complicated than simply undoing commits one after the other.

What I'm proposing is simple and can be improved and adapted over time to the specific needs of your project:

Use rebase instead of merge (merge only to mark the repository for something important, such as godot updates).

Prefer conventional commit, at least in the commit message, and adapt branch names accordingly.

 Example: 

`chore/merge-from-godot`  instead of “`merge-godot`”.
`feature/adopt-sdl-for-input`

Prefer an approach that resembles git-flow without necessarily respecting all its aspects:
a master branch
feature branches
tags to mark versions

the “/” separator allows you to organize branches in a folder if you're using a utility (I'll come back to this later)

This will allow you to automate many things, such as changelogs.
A good example of a repo is vue.js: https://github.com/vuejs/core

You can set up a “commit-msg” git hook to ensure that people respect conventional commit. 
cz is difficult to set up and at first completely passable.

here's an example of a git configuration along these lines:
```sh
    git config --global pull.rebase true
    git config --global rebase.autoStash true
    git config --global submodule.recurse true
    git config --global feature.manyFiles true
    git config --global core.untrackedcache true
    git config --global push.autoSetupRemote true
```
If you're not comfortable with `rebase -i` , I can only recommend the best graphical interfaces (and I've tried plenty for one project at Airbus)
it's :  https://git-fork.com/ 

For vscode I recommend mixing git Graph with gitlens (free version) and configuring the git editor for vscode ( git config core.editor “code --wait”)

This is my proposal, with which I can guarantee you'll have a clean repository that's easy to debug. You'll also be able to work asynchronously.

I can expand on this even further by talking about the fact that commits are just differences, branches are just sums of differences, and that by only making merges you increase the chances of deleting commits.

To reassure you even more, I remind you that nothing gets lost in git (thanks reflog).

Thanks you for reading.

Regards,
Obiwor

### Steps to reproduce

Simply clone this repo and `git fetch --all --prune`

### Minimal reproduction project (MRP)

N/A

**Comment by Linuxydable** [comment]
I agree !
