### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by Tim79000** [Redot-Engine/redot-engine#44]
dear github staff, this post was created to satirize conservatism, I do not stand for molesting children, as it is vile and disgusting, please do not banish me to GitHell

**Comment by LaraSQP** [comment]
I would volunteer to remove this type of post. They are timewasters. Let me know.

**Comment by GordofTheSandAgedPrince** [comment]
> I would volunteer to remove this type of post. They are timewasters. Let me know.

Yeah there are multiple post just trying to stall people right now.

**Comment by Tim79000** [comment]
You appear to not be bas

> I would volunteer to remove this type of post. They are timewasters. Let me know.

You appear to not be **_based_** enough, I suggest dissacociating with this project until you buy 25 guns and shoot 4 innocent black children, until then, you aren't welcome to participate in Redot discussion.

**Comment by damjancd** [comment]
Just report them and move on. Let's not let their sickness spread over

**Comment by Salvakiya** [comment]
Not productive... just spam
