### ISSUE TITLE
Add Poop

### ISSUE THREAD

**Issue by Tim79000** [Redot-Engine/redot-engine#49]
### Tested versions

1.0

### System information

Windos 5

### Issue description

i wish there was poop, maybe make the icon poop XD

### Steps to reproduce

open app, notice lack of poop

kill myself

### Minimal reproduction project (MRP)

what the heck is MRP?

**Comment by celerizer** [comment]
LGTM

**Comment by c0if** [comment]
i dont think queers poop

**Comment by Salvakiya** [comment]
spam/not useful
