### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by goober-183** [Redot-Engine/redot-engine#51]
### Tested versions

none, im not installing this

### System information

UwUntu Linux

### Issue description

I just want to know why make a fork, which is going to be a million commit's behind just cause the person running the godot engine account (and thats all they do(or did)) poking fun at one tweet about using game engines being 'Woke"
Like seriously, You guys are very inmmature.

### Steps to reproduce

Have person make a joke about anti-woke people on a big account about an open source project
Chaos ensues among the homophobes

### Minimal reproduction project (MRP)

nah

**Comment by LipusikTVK** [comment]
The issues on GitHub are not meant to ask such questions about the significance of the fork and so on. Contact the discord server or other social networks and close this problem. Don't do that again, please.

**Comment by Captain-Wet-Beard** [comment]
> Contact the discord server

What Discord server?
Also probably just report intentionally disruptive posts to Github support

**Comment by Spartan322** [comment]
I'd post the link to the server if not for the intentionally disruptive and bad faith actor of the OP.

**Comment by warcaninos** [comment]
Don't interact with bad faith actor just report them to github for miss use and close the Issue.

**Comment by dreamnook** [comment]
1. Fork is supported feature by Github. Hot repo like https://github.com/microsoft/vscode has 28.8K forks
2. There're 69.1K commits, not 1 million. If you hate cloning all commits, try `--depth 1` to speed up, or just wait official release.

**Comment by PorkDevMode** [comment]
It would be appreciated if you could keep politics out of the github **bug** section.

**Comment by tindrew** [comment]
This is why we can't have nice things.

**Comment by Tim79000** [comment]
_I will calcify your flesh and grind it over the abyss._
