### ISSUE TITLE
Crash with latest microsoft vs-redist

### ISSUE THREAD

**Issue by CSdiscoveries** [Redot-Engine/redot-engine#58]
### Tested versions

Specifying the version of the project is completely irrelevant lmfao. You fools couldn't even manage a single commit to change a file name or something? Is file management and right-clicking to rename files too woke for you?

### System information

trans rights OS

### Issue description

Yeah I actually dgaf about this, the title was just to make you think this was an actual issue. "Woke" was originally a word used to describe people who were aware of sources of opression and such; it still means that to a degree, regardless of what you people try to do. Turning "woke" into an insult is just an attempt at trying to opress people. And we won't have it. By the way, I'm a furry, and bisexual, and my significant other is transfem and also a furry. Are you too sensitive to cope with those facts? Are you gonna cry? Or are you going to sit and pretend like you're some big strong symbol of manlihood when in reality you're a pathetic degenerate, too scared of even the most harmless things? Grow up. And start realizing that every other person is just as valid of a person.

### Steps to reproduce

1. discover a blatant attempt by neonazis at lazily stealing the hard work of a bunch of people
2. title an issue report to maybe grab their attention, if they're even aware enough to notice 
3. enjoy at least inconveniencing them, if not hindering them more.

### Minimal reproduction project (MRP)

Couldn't even be bothered to change the issue template's references to the engine name huh? Whatever happened to all that talk of "woke liberals" having little work ethic and being lazy? I've watched absurdist comedies with characters that made more sense than you hypocritical dullards.

**Comment by abbe** [comment]
I am not sure what your point is supposed to be here? How is this fork "stealing" anything, if it's just a fork... and anyone can fork a FOSS project? Isn't that the point of open source?

**Comment by Spartan322** [comment]
Report the user and leave it to the maintainers, don't respond to these troll spam issues.

**Comment by newincpp** [comment]
I got new step to reproduce:
Step0: Create fork for political reason while saying they don't want politics in engine dev
Step1: get annoyed the first issues are about politics.

Love the energy @CSdiscoveries continue the nice work 💖

- A fellow lesbian.
