### ISSUE TITLE
Pathetic

### ISSUE THREAD

**Issue by Deftu** [Redot-Engine/redot-engine#61]
### Tested versions

Gay rights are human rights
Trans rights are human rights
Black lives matter

### System information

Gay rights are human rights. Trans rights are human rights. Black lives matter

### Issue description

Gay rights are human rights
Trans rights are human rights
Black lives matter

### Steps to reproduce

Gay rights are human rights
Trans rights are human rights
Black lives matter

### Minimal reproduction project (MRP)

Gay rights are human rights
Trans rights are human rights
Black lives matter

**Comment by FireBrandMint** [comment]
On main???????????????

**Comment by Deftu** [comment]
> On main???????????????

I don't see how it could be an issue, at all.

**Comment by xtrm-en** [comment]
> ### Tested versions
> 
> Gay rights are human rights Trans rights are human rights Black lives matter
> ### System information
> 
> Gay rights are human rights. Trans rights are human rights. Black lives matter
> ### Issue description
> 
> Gay rights are human rights Trans rights are human rights Black lives matter
> ### Steps to reproduce
> 
> Gay rights are human rights Trans rights are human rights Black lives matter
> ### Minimal reproduction project (MRP)
> 
> Gay rights are human rights Trans rights are human rights Black lives matter

absolute W

**Comment by FireBrandMint** [comment]
It means you heard from a friend of a friend of a friend a schizo rant and thought we were anti-something even though we have raimbow flaggers on our server. You're being ridiculous and moronic.

**Comment by Deftu** [comment]
> It means you heard from a friend of a friend of a friend a schizo rant and thought we were anti-something even though we have rainbow flaggers on our server. You're being ridiculous and moronic.

There is obvious anti-"woke" rhetoric in the project's issue replies and stargazer's profiles.

**Comment by FireBrandMint** [comment]
Anti-woke... so not wanting the project to follow a specific agenda is now wrong? Everything has to be political and appeal to your cause? What a narcisist. I'd not want someone like you power tripping on a goddam game engine, yes.

**Comment by Deftu** [comment]
> Anti-woke... so not wanting the project to follow a specific agenda is now wrong? Everything has to be political and appeal to your cause? What a narcisist. I'd not want someone like you power tripping on a goddam game engine, yes.

Thank you for proving my exact point. I don't see how my existence should be a political agenda, I'm simply fighting for my right to exist as I am without fools such as yourself attempting to hurt me. If you can't suck it up and live with that, then you're the one trying to push an agenda. Hence why I call this project pathetic and sad.

**Comment by MathyFey** [comment]
> > Anti-woke... so not wanting the project to follow a specific agenda is now wrong? Everything has to be political and appeal to your cause? What a narcisist. I'd not want someone like you power tripping on a goddam game engine, yes.
> 
> Thank you for proving my exact point. I don't see how my existence should be a political agenda, I'm simply fighting for my right to exist as I am without fools such as yourself attempting to hurt me. If you can't suck it up and live with that, then you're the one trying to push an agenda. Hence why I call this project pathetic and sad.

Which part of this is part of your existence? This is just a github page, what the heck...

**Comment by FireBrandMint** [comment]
You're not fighting for your right to exist, right now you're sitting on your ass on your computer pathetically typing on a innocent repo that it has to privilige you and represent you. A narcisist demanding to be given the spotlight pretending to be a knight of honor, no point to prove, no cause to fight for.

**Comment by zakanater19** [comment]
yawn

**Comment by Deftu** [comment]
> You're not fighting for your right to exist, right now you're sitting on your ass on your computer pathetically typing on a innocent repo that it has to privilige you and represent you. A narcisist demanding to be given the spotlight pretending to be a knight of honor, no point to prove, no cause to fight for.

I'm not demanding anything. I am simply pointing out the fact that this project was forked from Godot out of a need to pull it out of the maintainers' hands BECAUSE of a "woke agenda".

Regardless, I don't see how that insult is meant to say anything about me, considering you're doing the same thing to try to combat it? If anything, it makes the situation worse for you seeing as this project wouldn't exist without someone, somewhere, sitting on their ass and thinking "I hate Godot for being woke, I should fork it and make my own"

**Comment by FireBrandMint** [comment]
God, you literally implied your existence is part of woke, do you not even know what you're talking about? Do you not know what anti-woke means or will you redefine it? Do you not know what an open source project is and that Godot will keep their repo and rights all the same? Are you talking without knowing anything?

Is your only argument trying to pretend you do not know anything? Pretending you're dumb makes you look dumb.

Combat it? You don't have any power, what am i fighting? I'm basically just telling you what you're doing.

**Comment by pulpdev** [comment]
> > Anti-woke... so not wanting the project to follow a specific agenda is now wrong? Everything has to be political and appeal to your cause? What a narcisist. I'd not want someone like you power tripping on a goddam game engine, yes.
> 
> Thank you for proving my exact point. I don't see how my existence should be a political agenda, I'm simply fighting for my right to exist as I am without fools such as yourself attempting to hurt me. If you can't suck it up and live with that, then you're the one trying to push an agenda. Hence why I call this project pathetic and sad.

Our existence isn't a political agenda either. We're also fighting for our right to exist. Can you please give us the same respect? Thanks. I'm attempting to take you seriously, despite your childish shitpost that doesn't help anyone at all.

**Comment by jlitewski** [comment]
Redot is, at it's core, a piece of software. It does not care about, nor should it care about, anyone's opinion, gender, political affinity, viewpoints, identity, or anything other than the underlying code of the project itself. The same should go for the developers of Redot, as well as the community. If a piece of software threatens core aspects of you and/or identity because it doesn't directly align with how you _**personally feel**_, the issue isn't the software. You are a living, breathing human being.

**Comment by ChanceNCounter** [comment]
> Our existence isn't a political agenda either. We're also fighting for our right to exist.

Absolutely everything else aside, this was a disgusting reply to someone who is *literally* fighting for their right to exist, like, as a not-dead organism on Earth.

**Comment by GordofTheSandAgedPrince** [comment]
Correction, Redot is for anyone to use anyone at all. The point isn’t to take anyone out of the game making space but to get rid of ANYONES FORCED AGENDAS.

**Comment by ChanceNCounter** [comment]
TIL "it's okay to be gay" is an agenda!

**Comment by Miguel0Almeida** [comment]
So all the antitrans posts from Redot creator is not a Political Thing?
Even atacks agains Imane are Political neutral?

![Screenshot 2024-10-02 at 11-49-21 drew (@Andevrs) _ X](https://github.com/user-attachments/assets/1f8053f9-b4a5-471b-92cb-83657e13d73
![Screenshot 2024-10-02 at 10-51-22 drew (@Andevrs) _ X](https://github.com/user-attachments/assets/0deb3f3f-ab90-4518-8473-f8bf2cc6b225)
d)
![Screenshot 2024-10-02 at 11-21-13 drew (@Andevrs) _ X](https://github.com/user-attachments/assets/d287f595-16fa-42bc-ae5e-bc36164721dc)
![Screenshot 2024-10-02 at 11-16-17 drew (@Andevrs) _ X](https://github.com/user-attachments/assets/bb6ec9e4-854a-41ed-9200-5720ccb4274c)

![Screenshot 2024-10-02 at 10-51-33 drew (@Andevrs) _ X](https://github.com/user-attachments/assets/bcc6fe8e-9dcc-4b16-9655-b327b5340fd6)

**Comment by Deftu** [comment]
Welp, there it is. Pathetic, as I said.

**Comment by vktf1** [comment]
![image](https://github.com/user-attachments/assets/8970fb3a-bddd-41a0-97a9-000e77314015)
![image](https://github.com/user-attachments/assets/e0ce7c7c-180f-4db9-9375-567346e595b6)
