### ISSUE TITLE
Switch License to Unlicense

### ISSUE THREAD

**Issue by musicalskele** [Redot-Engine/redot-engine#639]
### Tested versions

N/A

### System information

N/A

### Issue description

This fork is built upon the foundation laid by the Godot Engine contributors, however it’s time for us to take a bold, necessary step forward: switching to the Unlicense. Why? Because the Unlicense *represents true freedom* for software development. It offers *complete and unrestricted public domain dedication*, which is the future of open, unrestricted collaboration in a world where licenses are too often bogged down by unnecessary legal intricacies.

### Why the Unlicense?

- **Total Freedom**: No strings attached. *Anyone* can use, modify, or distribute this code without having to worry about obscure clauses or legal obligations. The Unlicense is the ultimate declaration of trust in the community—let innovation flourish without barriers.
  
- **Avoid the Legal Bloat**: The MIT license, while permissive, still comes with baggage in terms of liability disclaimers and copyright clauses. The Unlicense wipes the slate clean, giving users full control with no unnecessary overhead. It's time to shed those legal chains.

### Addressing Concerns:

1. **“But the MIT license is fine!”**
   - The MIT license is restrictive *compared to* the Unlicense. Even small legal constraints can slow down adoption or create friction. The Unlicense is *pure* public domain dedication—no restrictions, no confusion.

2. **“What about liability?”**
   - The Unlicense still provides the standard "AS IS" disclaimer. We won’t be liable for misuse or issues with the code, just like the MIT license. We don’t lose any legal protection, but we gain complete openness.

3. **“Why change something that works?”**
   - Innovation thrives when boundaries are pushed. The Unlicense reflects the cutting-edge philosophy of removing all barriers between code and creativity. We refuse to settle for "good enough." We're taking this project to the next level of open source.

---

Switching to the Unlicense is not just a move—it's a statement. We must be committed to making this project as accessible, open, and frictionless as possible. Let's make it official.

Here is the text for the Unlicense:

```txt
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org/>
```

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by Starkium** [comment]
do you mean for any code that Redot makes on its own?

**Comment by Nyaa-rlathotep** [comment]
Unlicense is even worse than MIT licensed. The point of licenses like the GPL is to ensure the freedom continues down the line. Unlicense and MIT fundamentally do not protect freedom the same way. They trade short-term increased freedom for long term less freedom, since anyone can just take the code and make a proprietary version that is totally locked down and anti-freedom.

MIT is already weak enough for anything anyone would want to use the code for. Switching to unlicense just makes it worse with no upside whatsoever.

**Comment by heavymetalmixer** [comment]
This would make it even harder to get a chance for console exports.

**Comment by MisterPuma80** [comment]
This is a troll trying to create legal landmines for the project. You can't change MIT licensed code without permission. No one uses the Unlicense in anything serious. MIT is fine.

**Comment by musicalskele** [comment]
> This is a troll trying to create legal landmines for the project. You can't change MIT licensed code without permission. No one uses the Unlicense in anything serious. MIT is fine.

First off, calling me a troll for trying to offer more licensing options is completely off-base. This isn’t some sneaky attempt to mess things up—it's about giving new code more freedom while keeping the old code under MIT. 
```
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
```
As you can read it is possible to sublicense MIT. MIT-licensed code stays MIT, period. New code, however, will be under the Unlicense, which is basically 'do whatever you want with it.' If people want to stick with MIT, they’re free to. This isn’t some ‘legal landmine,’ it’s just offering more freedom to the open-source world.

And yeah, people do use the Unlicense in serious projects—it’s literally a way to put code in the public domain. So, no, this isn't trolling, just giving more options. End of story. Be more open to ideas.

**Comment by dandykong** [comment]
> This is a troll trying to create legal landmines for the project. You can't change MIT licensed code without permission. No one uses the Unlicense in anything serious. MIT is fine.

Same exact troll who wanted to put adware in.

**Comment by 8bitprodigy** [comment]
While I do believe Unlicense is superior, I doubt it would be able to happen any time soon. That said, it *could* be possible to change the license if any new contributions are under the Unlicense and eventually all the original MIT-licensed code gets replaced. However, considering how Redot plans to pull features from Godot for some time, such a thing would take quite a while to happen.

**Comment by 8bitprodigy** [comment]
> Unlicense is even worse than MIT licensed. 

Quite the opposite, it's much better, as it gives developers more freedom to use the code how they wish.

> The point of licenses like the GPL is to ensure the freedom continues down the line. Unlicense and MIT fundamentally do not protect freedom the same way. 

MIT and Unlicense aren't licenses *like* GPL. GPL is *copyleft*, whereas Unlicense/MIT are *permissive* licenses, and as such, better respect human nature not only to want to share, but also to keep secrets if one so sees fit.

> They trade short-term increased freedom for long term less freedom, since anyone can just take the code and make a proprietary version that is totally locked down and anti-freedom.

This is fundamentally false. One cannot swoop in and relicense someone else's project, it only allows them to not have to share the code to any changes they make, should they wish to create their own fork, and that's fine--such features could always be copied by the FOSS community and reimplemented into the original project.

> MIT is already weak enough for anything anyone would want to use the code for. Switching to unlicense just makes it worse with no upside whatsoever.

Also false. MIT requires one to retain notice and acknowledgements to the project in any derivative product, and these can accumulate over time. Unlicense, on the other hand, does not force such a responsibility on anyone who wishes to create a derivative. The Unlicense gives developers more freedom to focus on what matters most--the code.

**Comment by musicalskele** [comment]
> > This is a troll trying to create legal landmines for the project. You can't change MIT licensed code without permission. No one uses the Unlicense in anything serious. MIT is fine.
> 
> Same exact troll who wanted to put adware in.

ad hominem

**Comment by RaidyQK** [comment]
> Use the unlicense
> Copy-paste the code
> "ididit"
> Put non-permissive license
> Sue any other Redot fork

Now, that would be illegal because we inherit Godot code. Our tool isnt made for "freedom", it is meant to be an apolitical tool.

**Comment by RaidyQK** [comment]
> > > This is a troll trying to create legal landmines for the project. You can't change MIT licensed code without permission. No one uses the Unlicense in anything serious. MIT is fine.
> > 
> > Same exact troll who wanted to put adware in.
> 
> ad hominem 

You call them disrespectful, but not liars.

Weren't the LGBT community supposed to be the tolerant and acceptable one?

**Comment by musicalskele** [comment]
> > > > This is a troll trying to create legal landmines for the project. You can't change MIT licensed code without permission. No one uses the Unlicense in anything serious. MIT is fine.
> > > 
> > > Same exact troll who wanted to put adware in.
> > 
> > ad hominem 
> 
> You call them disrespectful, but not liars.
> 
> Weren't the LGBT community supposed to be the tolerant and acceptable one?

Stop bringing politics into the discussion.

**Comment by musicalskele** [comment]
> > Use the unlicense
> > Copy-paste the code
> > "ididit"
> > Put non-permissive license
> > Sue any other Redot fork
> 
> Now, that would be illegal because we inherit Godot code. Our tool isnt made for "freedom", it is meant to be an apolitical tool.

what are you talking about

**Comment by DrLegitamate** [comment]
You dont even use the license for your own projects. If you were serious about it then you would lead by example

**Comment by musicalskele** [comment]
> You dont even use the license for your own projects. If you were serious about it then you would lead by example. So far all of your contributions to this git have been insidious of nature.

Why the hell are you mentioning my projects how is that related to the subject. If you want a serious project made with unlicensed, there's libdragon.

**Comment by musicalskele** [comment]
there was no real discussion taking place here and everyone attacked me for "being a troll", this is just like godot you guys are focusing on drama rather than code i only suggested a license change and you guys cant even listen to this idea and instead of disagreeing you attack me, it's very divisive
now the issue is closed for no good reason

**Comment by musicalskele** [comment]
i request the issue to be reopened this is oppression

**Comment by DrLegitamate** [comment]
You havent even starred Redot. You obviously have no intention of following the project. Why do you insist of adding insidious features?

![image](https://github.com/user-attachments/assets/df2cd2ee-1d9a-4884-bb67-67d6fcac2eb6)

**Comment by musicalskele** [comment]
> You havent even starred Redot. You obviously have no intention of following the project. Why do you insist of adding insidious features?
> 
> ![image](https://github.com/user-attachments/assets/df2cd2ee-1d9a-4884-bb67-67d6fcac2eb6)
> 

I have not starred projects I've literally forked what's your point you're just trying to attack me for no reason.

**Comment by DrLegitamate** [comment]
> > You havent even starred Redot. You obviously have no intention of following the project. Why do you insist of adding insidious features?
> > 
> > ![image](https://github.com/user-attachments/assets/df2cd2ee-1d9a-4884-bb67-67d6fcac2eb6)
> > 
> 
> I have not starred projects I've literally forked what's your point you're just trying to attack me for no reason.

Ive criticised your insidious additions to the project (of which the fork was needed for). I haven't attacked you personally unless you purposefully tried and make the project worse.

**Comment by musicalskele** [comment]
> > > You havent even starred Redot. You obviously have no intention of following the project. Why do you insist of adding insidious features?
> > > 
> > > ![image](https://github.com/user-attachments/assets/df2cd2ee-1d9a-4884-bb67-67d6fcac2eb6)
> > > 
> > 
> > I have not starred projects I've literally forked what's your point you're just trying to attack me for no reason.
> 
> Ive criticised your insidious additions to the project (of which the fork was needed for). I haven't attacked you personally unless you purposefully tried and make the project worse.

ok troll

**Comment by musicalskele** [comment]
> > > > > You havent even starred Redot. You obviously have no intention of following the project. Why do you insist of adding insidious features?
> > > > > ![image](https://private-user-images.githubusercontent.com/115639007/375803623-df2cd2ee-1d9a-4884-bb67-67d6fcac2eb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDYyMzUsIm5iZiI6MTcyODc0NTkzNSwicGF0aCI6Ii8xMTU2MzkwMDcvMzc1ODAzNjIzLWRmMmNkMmVlLTFkOWEtNDg4NC1iYjY3LTY3ZDZmY2FjMmViNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxNTEyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDMzNGM4Y2Y0ZTNjMTg0YTdmZDA0ZGJlOTg4MjZiMWZmMTcwNTcyNTRkYTUwYTc1ZDQ4OTExOTZlMDNiMTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L86e7utotY5_yR5KG7zABmbVbXsQ11Bcrq715yF565o)
> > > > 
> > > > 
> > > > I have not starred projects I've literally forked what's your point you're just trying to attack me for no reason.
> > > 
> > > 
> > > Ive criticised your insidious additions to the project (of which the fork was needed for). I haven't attacked you personally unless you purposefully tried and make the project worse.
> > 
> > 
> > ok troll
> 
> Did you criticise others for chucking the word troll around?

stop harassing me troll

**Comment by zakanater19** [comment]
> ad hominem

![36569350](https://github.com/user-attachments/assets/9e39a1e4-c0d1-4df5-a8e0-1072b738343d)

**Comment by musicalskele** [comment]
> > ad hominem
> 
> ![36569350](https://github.com/user-attachments/assets/9e39a1e4-c0d1-4df5-a8e0-1072b738343d)
> 

?
