### ISSUE TITLE
Stop lying you ADMITE WHAT YOU ARE COWARDS.

### ISSUE THREAD

**Issue by Miguel0Almeida** [Redot-Engine/redot-engine#65]
### Tested versions

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/d703bafe-54a3-4cb7-a933-318c97188004)

Free Speech you do review bombing on Godot I call you what you are COWARDS
![Captura de tela de 2024-10-02 14-33-29](https://github.com/user-attachments/assets/c5886bed-deed-4d64-a50a-324cd582446d)

### System information

YOU ARE A COWARD DREW  AND ITS JUST FREE SPEECH

### Issue description

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/d703bafe-54a3-4cb7-a933-318c97188004)

Free Speech you do review bombing on Godot I call you what you are COWARDS
![Captura de tela de 2024-10-02 14-33-29](https://github.com/user-attachments/assets/c5886bed-deed-4d64-a50a-324cd582446d)

### Steps to reproduce

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/d703bafe-54a3-4cb7-a933-318c97188004)

Free Speech you do review bombing on Godot I call you what you are COWARDS
![Captura de tela de 2024-10-02 14-33-29](https://github.com/user-attachments/assets/c5886bed-deed-4d64-a50a-324cd582446d)

### Minimal reproduction project (MRP)

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/d703bafe-54a3-4cb7-a933-318c97188004)

Free Speech you do review bombing on Godot I call you what you are COWARDS
![Captura de tela de 2024-10-02 14-33-29](https://github.com/user-attachments/assets/c5886bed-deed-4d64-a50a-324cd582446d)

**Comment by GordofTheSandAgedPrince** [comment]
Just contact someone to remove this post don't give any attention

**Comment by Miguel0Almeida** [comment]
COWARDS

**Comment by Miguel0Almeida** [comment]
HEHEHE ITS FUNNY

![in days like this](https://github.com/user-attachments/assets/3ed826f3-3b75-480e-a9fa-ba9b3c910173)
UNNY


> Just contact someone to remove this post don't give any attention

JUST FREE SPEECH

**Comment by Trismegiste** [comment]
Reported for spamming

Programming is rational process, therefore has nothing to do with politics
