### ISSUE TITLE
STOP BE COWARD DREW TALK I CLEAR FOR EVERYONE

### ISSUE THREAD

**Issue by Miguel0Almeida** [Redot-Engine/redot-engine#66]
### Tested versions

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/d703bafe-54a3-4cb7-a933-318c97188004)

Free Speech you do review bombing on Godot I call you what you are COWARDS
![Captura de tela de 2024-10-02 14-33-29](https://github.com/user-attachments/assets/c5886bed-deed-4d64-a50a-324cd582446d)

### System information

STOP BE A COWARD DREW

### Issue description

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/d703bafe-54a3-4cb7-a933-318c97188004)

Free Speech you do review bombing on Godot I call you what you are COWARDS
![Captura de tela de 2024-10-02 14-33-29](https://github.com/user-attachments/assets/c5886bed-deed-4d64-a50a-324cd582446d)

### Steps to reproduce

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/d703bafe-54a3-4cb7-a933-318c97188004)

Free Speech you do review bombing on Godot I call you what you are COWARDS
![Captura de tela de 2024-10-02 14-33-29](https://github.com/user-attachments/assets/c5886bed-deed-4d64-a50a-324cd582446d)

### Minimal reproduction project (MRP)

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/d703bafe-54a3-4cb7-a933-318c97188004)

Free Speech you do review bombing on Godot I call you what you are COWARDS
![Captura de tela de 2024-10-02 14-33-29](https://github.com/user-attachments/assets/c5886bed-deed-4d64-a50a-324cd582446d)

**Comment by FireBrandMint** [comment]
My god, what a mental breakdown!
