### ISSUE TITLE
(Redot sometimes crashed on Linux) ERROR: Index p_screen = -5 is out of bounds 

### ISSUE THREAD

**Issue by mcdubhghlas** [Redot-Engine/redot-engine#667]
### Tested versions

v4.4.dev.custom_build.5e7e5fc60

### System information

Linux - v4.4.dev.custom_build.5e7e5fc60 - Any

### Issue description

Opening a project will have it lock up and I'll have to cast `kill $pid`

It's the same issue here: https://github.com/godotengine/godot/issues/27195

### Steps to reproduce

Open a project.

### Minimal reproduction project (MRP)

Just open a project.

**Comment by SkogiB** [comment]
Did you try the update/regenerate cache suggestion of the user early in that issues life?

**Comment by mcdubhghlas** [comment]
That's from another user in the chat, I just made this for them.

**Comment by Spartan322** [comment]
The system information isn't enough and there is no way to know who the user is without at least some contact info if they don't even have a github account.

**Comment by Spartan322** [comment]
Closing because there is no way to resolve this with the information we were given and the related issue was resolved with the same response.
