### ISSUE TITLE
Error: Couldn't load project data at path ".". Is the .pck file missing?

### ISSUE THREAD

**Issue by MrOzwaldMan** [Redot-Engine/redot-engine#673]
### Tested versions

Introduced  in `5e7e5fc `

### System information

Ubuntu 24.10

### Issue description

Getting Error: `Couldn't load project data at path ".". Is the .pck file missing?` when running a Linux build of the engine. However, running the [redot-linuxbsd](https://github.com/Redot-Engine/redot-engine/releases/download/2024101114/redot-linuxbsd.zip) fixes the issue.

### Steps to reproduce

Running the Linux build. I don't if it happens on the other machines, can people confirm?

### Minimal reproduction project (MRP)

N/A

**Comment by SkogiB** [comment]
Make sure you're running the editor, not the template. The template is *strictly* for exporting your builds, you link it as your custom release template. There's a note on the release page as well if you need to refer back to it. If this is occurring when running the editor, we need to look into it

![image](https://github.com/user-attachments/assets/ec253c34-083c-43f9-8b63-782717bfa9e6)

**Comment by Spartan322** [comment]
The editor builds should be more obviously the ones to download, we also need to fix downloading templates for our stuff.

**Comment by SkogiB** [comment]
> The editor builds should be more obviously the ones to download, we also need to fix downloading templates from the interface. This is a repo UX problem.

Yep, this is an issue caused by just the setup not being obvious and us not having the backend of pulling export templates automatically
