### ISSUE TITLE
Engine crashes on use a texture without mipmaps

### ISSUE THREAD

**Issue by TheFirstInvoker** [Redot-Engine/redot-engine#691]
### Tested versions

-Reproducible on Redot 4.4 Beta Release
-Not reproducible in previous versions

### System information

Windows 10 - Redot 4.4 Beta Release - Compatibility Render - AMD Radeon (TM) R4 Graphics

### Issue description

Engine crashes when puts a texture on a spatial material texture slot. This doesn't occurs if the texture have already generated mipmaps on import settings. Engine will keep crashing if you try to re-open the project, unless you delete the image .import file. I must emphasize that I'm running the editor on Compatibility Render, as my old computer doesn't support Vulkan or other render modes.

### Steps to reproduce

1- Create a MeshInstance3D node and add it a new mesh.
2- Add a new StandardMaterial3D
3- Add an imported image to the albedo_texture slot.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/17350920/test.zip)

**Comment by SkogiB** [comment]
Could you do me a favor and attempt this with Godot's 4.4 dev build? We're aware of a LOT of bugs in their 4.4 build that we inherited, virtually all of the bugs people have been reporting. This is why we're working on a 4.3 stable rebrand as well, so these can be mitigated as it really messes up our perception of what our own changes are doing. Appreciate the feedback!

**Comment by TheFirstInvoker** [comment]
Sure. Tested on Godot 4.4 dev 1, a notification pops up with the following message "Texture detected as used in 3D. Enabling mipmap generation and setting the texture compression mode to VRAM Compressed (S3TC/ETC/BPTC)", however, engine doesn't crash

**Comment by SkogiB** [comment]
> Sure. Tested on Godot 4.4 dev 1, a notification pops up with the following message "Texture detected as used in 3D. Enabling mipmap generation and setting the texture compression mode to VRAM Compressed (S3TC/ETC/BPTC)", however, engine doesn't crash

Gotcha, thank you, we'll take a look at this as soon as we can.

**Comment by Spartan322** [comment]
This might have a Godot issue depending on whether a PR solved it before it was reported.

**Comment by SkogiB** [comment]
@TheFirstInvoker If you check this again on our more recent master artifacts let us know, that will help identify if a PR upstream fixed it or not.
