### ISSUE TITLE
get_world_3d().direct_space_state.intersect_ray() can't get the value.

### ISSUE THREAD

**Issue by suoyukii** [Redot-Engine/redot-engine#695]
### Tested versions

4.4 Beta ( 2024101114 )

### System information

Windows 11 - Redot v4.4 Beta (2024101114) - Vulkan (Forward+)

### Issue description

I ported my game from `Godot` version `4.3` to `Redot` and found this bug.

|||
|-|-|
|GDScript|get_world_3d().direct_space_state.intersect_ray()|
|C#|GetWorld3D().DirectSpaceState.IntersectRay()|

I've tried it with `Redot` and `Godot`'s `GDScript` and `C#` respectively, but only `Redot` can't get the value, and it's all `{  }`.
I also downloaded `Godot` `4.4-dev3` and tried it, and `Godot` works fine, so I'm sure it's a `Redot` bug.

### Steps to reproduce

- GDScript code:
```gdscript
	var mouse_postion = get_viewport().get_mouse_position();
	var from = project_ray_origin(mouse_postion);
	var to = from + project_ray_normal(mouse_postion) * 100;
	var ray_query = PhysicsRayQueryParameters3D.create(from, to);
	var raycast_result = get_world_3d().direct_space_state.intersect_ray(ray_query);
	print("Iget_world_3d().direct_space_state.intersect_ray() = ", raycast_result);
```

- C# code:
```csharp
        var mouse_postion = GetViewport().GetMousePosition();
        var from = ProjectRayOrigin(mouse_postion);
        var to = from + ProjectRayNormal(mouse_postion) * 100;
        var ray_query = new PhysicsRayQueryParameters3D();
        ray_query.From = from;
        ray_query.To = to;
        var raycast_result = GetWorld3D().DirectSpaceState.IntersectRay(ray_query);
        GD.Print("GetWorld3D().DirectSpaceState.IntersectRay() = ", raycast_result);
```

### Minimal reproduction project (MRP)

[bug.zip](https://github.com/user-attachments/files/17355222/bug.zip)

The `zip file` contains both `GDScript` and `C#` code for the project, the `default` is `GDScript`, switching to `C#` only requires modifying the `script properties`.

**Comment by SkogiB** [comment]
Thank you for doing the legwork to check Godot on those fronts, it helps us diagnose this stuff a LOT. We'll be taking a look at this once we have the 4.3 stable build out and can direct efforts towards 4.4 stuff. We may even have some downtime waiting on build pipeline fixes to get a guy looking into it before the 4.3 build drops. Thanks again man

**Comment by TheEclectus** [comment]
@suoyukii Your MRP doesn't seem to have any colliders in your scene, so I'm getting identical behavior between Godot 4.3, Godot 4.4-dev3, and Redot 4.4 beta, which is a stream of empty dictionaries being printed out. Adding a collider (StaticBody3D with a CollisionShape3D) gives consistent, correct behavior as well, where a populated dictionary of collisions is printed out. 

Does your project have colliders that the MRP doesn't?

**Comment by suoyukii** [comment]
> 您的 MRP 在您的场景中似乎没有任何碰撞器，因此我在 Godot 4.3、Godot 4.4-dev3 和 Redot 4.4 beta 之间获得了相同的行为，这是一堆打印出来的空字典。添加碰撞器（带有 CollisionShape3D 的 StaticBody3D）也会提供一致、正确的行为，其中会打印出填充的碰撞字典。
> 
> 您的项目是否有 MRP 没有的碰撞器？

Thank you, my project was imported using a blender model and I forgot to enable the physics option.

**Comment by suoyukii** [comment]
> @suoyukii Your MRP doesn't seem to have any colliders in your scene, so I'm getting identical behavior between Godot 4.3, Godot 4.4-dev3, and Redot 4.4 beta, which is a stream of empty dictionaries being printed out. Adding a collider (StaticBody3D with a CollisionShape3D) gives consistent, correct behavior as well, where a populated dictionary of collisions is printed out.
> 
> Does your project have colliders that the MRP doesn't?

Thank you, my project was imported using a blender model and I forgot to enable the physics option.
