### ISSUE TITLE
Multi Threading Bug

### ISSUE THREAD

**Issue by Nightmare1984** [Redot-Engine/redot-engine#696]
### Tested versions

4.4.dev

### System information

ArchLinux - Redot V4.4.0.dev 

### Issue description

Multi Threading Bug Here's A Image 
![Bug_Report](https://github.com/user-attachments/assets/df7e6300-6fe0-444b-87a7-20861f9f37a8)

### Steps to reproduce

Turn On Multi Threading After making a Gui Press Test Button Then Should Just Give Black Screen

### Minimal reproduction project (MRP)

[multi-threading-bug.zip](https://github.com/user-attachments/files/17355306/multi-threading-bug.zip)

**Comment by SkogiB** [comment]
Could be an issue with our linux builds (already being worked on) OR from Godot upstream. Hard to say, thank you for notifying us of it. If you have time, could you take a peak at Godot's issues to see if the same thing is happening up there? Would help us diagnose a lot. Thanks again

**Comment by Nightmare1984** [comment]
same issue in godot repo issues
https://github.com/godotengine/godot/issues/98284
