### ISSUE TITLE
Shader Editor Scrollview Bug

### ISSUE THREAD

**Issue by SwissCore92** [Redot-Engine/redot-engine#704]
### Tested versions

redot 4.4.dev, 
godot 4.4.dev3 

### System information

Windows 11

### Issue description

The scrollview of the shader editor can miscalculate the scrollcontainer height, preventing you to scroll down to the bottom of the script.

Edit: this bug is also present in the latest godot dev build

### Steps to reproduce

1. open a shader script
2. collapse a large function
3. delete or cut the function while it is collapsed
4. undo or paste the function back
5. try scroll to the bottom of the script

https://github.com/user-attachments/assets/b5687ba1-f758-43b0-9088-b40a7307ff44

### Minimal reproduction project (MRP)

[shader_edit_mrp.zip](https://github.com/user-attachments/files/17361125/shader_edit_mrp.zip)

**Comment by SkogiB** [comment]
As it's a godot bug, I'll close the issue since we just have to wait for them to finish fixing it, thank you for notifying us though!

**Comment by SwissCore92** [comment]
Just discovered, this issue also applies to the script editor.
