### ISSUE TITLE
Kaetram typo in the README.

### ISSUE THREAD

**Issue by andradei** [Redot-Engine/redot-engine#711]
### Tested versions

N/A

### System information

N/A

### Issue description

The REAMDE.md of the repository has a typo. The name of the game is Kaetram, the REAMDE has Keatram.

### Steps to reproduce

See screenshot

![image](https://github.com/user-attachments/assets/5b1dacdb-95f7-4657-9aa9-e657d8946ffd)

### Minimal reproduction project (MRP)

N/A

**Comment by SkogiB** [comment]
damn CALLED OUT
