### ISSUE TITLE
Investigate possible problems caused by "Using Godot;" being changed to "using Redot;" in docs/translations files

### ISSUE THREAD

**Issue by SkogiB** [Redot-Engine/redot-engine#712]
Just a note for the core crew so we don't forget
4.3 and 4.4dev

**Comment by Majoramari** [comment]
We should revert it to Using godot; because the code "using Redot;" is not valid
![image](https://github.com/user-attachments/assets/65317a04-57e9-4164-b8d4-f9930b9b448c)

**Comment by ActuallyTheOwner** [comment]
If anything has already changed, we should not go back on it.
A hard fork early on might prove beneficial and makes Redot distinct from Godot.

**Comment by Spartan322** [comment]
It should be use Godot, we are not intending to breaking compatibility with Godot any time soon, and with stuff like this we likely never will.
