### ISSUE TITLE
Path of browser not changed

### ISSUE THREAD

**Issue by cynerboy** [Redot-Engine/redot-engine#719]
### Tested versions

v4.4.dev.mono.gh[1c7d7fa8d]

### System information

Windows 10 - v4.4.dev.mono.gh[1c7d7fa8d]

### Issue description

I can't change the path with typing.

I try to change directory with writing path. But after enter typing true path not applyied in this version.

This issue was not on godot 4.3 stable

### Steps to reproduce

![bugredot](https://github.com/user-attachments/assets/85c4c5cc-25c9-4b27-9220-58d170af7559)

### Minimal reproduction project (MRP)

Thanks.

**Comment by Majoramari** [comment]
Dumb question do you press enter?

> Note: This issue is not occurring in Linux v4.4.alpha.custom_build [7894cd1a5].

**Comment by Spartan322** [comment]
I cannot replicate this for v4.4.dev.custom_build [5e7e5fc60]

**Comment by SkogiB** [comment]
> > Dumb question do you press enter?
> > > Note: This issue is not occurring in Linux v4.4.alpha.custom_build [[7894cd1](https://github.com/Redot-Engine/redot-engine/commit/7894cd1a5a680020c51e0df96ce8675ad647d91b)].
> 
> Yes my friend. You can check that. I try to show you in gif. This was worked really well on godot engine 4.3 I hope this issue fix in the future.

Check if it also occurs in Godot 4.4dev please, this issue also sounds like one we inherited.

**Comment by cynerboy** [comment]
> > > Dumb question do you press enter?
> > > > Note: This issue is not occurring in Linux v4.4.alpha.custom_build [[7894cd1](https://github.com/Redot-Engine/redot-engine/commit/7894cd1a5a680020c51e0df96ce8675ad647d91b)].
> > 
> > 
> > Yes my friend. You can check that. I try to show you in gif. This was worked really well on godot engine 4.3 I hope this issue fix in the future.
> 
> Check if it also occurs in Godot 4.4dev please, this issue also sounds like one we inherited.

Yes, I tried it now. This problem also exists in the latest version of "Godot Engine" (Godot_v4.4-dev3_mono_official [f4af8201b] win_64).

**Comment by SkogiB** [comment]
> > > > Dumb question do you press enter?
> > > > > Note: This issue is not occurring in Linux v4.4.alpha.custom_build [[7894cd1](https://github.com/Redot-Engine/redot-engine/commit/7894cd1a5a680020c51e0df96ce8675ad647d91b)].
> > > 
> > > 
> > > Yes my friend. You can check that. I try to show you in gif. This was worked really well on godot engine 4.3 I hope this issue fix in the future.
> > 
> > 
> > Check if it also occurs in Godot 4.4dev please, this issue also sounds like one we inherited.
> 
> Yes, I tried it now. This problem also exists in the latest version of "Godot Engine" (Godot_v4.4-dev3_mono_official [[f4af820](https://github.com/Redot-Engine/redot-engine/commit/f4af8201bac157b9d47e336203d3e8a8ef729de2)] win_64).

Alright, thanks for the leg work. This pretty much guarantees that it is a bug caused by their work upstream on Godot 4.4dev and means we simply have to wait for them to fix it as well. Unfortunate, but that is the reality. Standby for a stable 4.3 build from us!

**Comment by Spartan322** [comment]
I don't think the bug necessarily needs to be closed, just linked to the Godot issue.
