### ISSUE TITLE
Cannot freely set animation step values in the animation timeline editor. It changes to multiples of 0.0625.

### ISSUE THREAD

**Issue by AnnanDistance** [Redot-Engine/redot-engine#720]
### Tested versions

Reproducible in Redot v4.4.dev (5e7e5fc60) 

### System information

Redot v4.4.dev (5e7e5fc60) - Windows 10.0.19045 - Multi-window, 1 monitor - OpenGL ES 3/ANGLE (Compatibility) - AMD Radeon HD 8600/8700M (Advanced Micro Devices, Inc.; 27.20.20913.2000) - Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 threads)

### Issue description

In the animation timeline editor, it is not possible to set animation step values (in seconds not fps) to values that are not combinations of 1/16 1/8 1/4 or 1/2.

Example : If I enter 0.05 it changes to 0.0625. If I enter 0.1 it changes to 0.125.

### Steps to reproduce

-Add animation player, 
-add new animation,
-make sure timeline units is in seconds (not FPS),
-try to change the animation step value.

![Redot4 4issueAnimSnap](https://github.com/user-attachments/assets/d452b321-81bd-45c3-bcf0-407621bd92ef)

### Minimal reproduction project (MRP)

NA

**Comment by Spartan322** [comment]
Does this occur in Godot's 4.4 dev3 release?

**Comment by SkogiB** [comment]
> Where do I get the dev3 release?

Pull it from their github, basically. I think their website also links to dev builds? This sounds like a Godot 4.4dev problem that we inherited

**Comment by AnnanDistance** [comment]
> Does this occur in Godot's 4.4 dev3 release?

I misread that as Redot 4.4 dev3. That's why I couldn't find it.

The issue is not there in Godot 4.4 dev3.

**Comment by SkogiB** [comment]
> > Does this occur in Godot's 4.4 dev3 release?
> 
> I misread that as Redot 4.4 dev3. That's why I couldn't find it.
> 
> The issue is not there in Godot 4.4 dev3.

Alright, thank you, we'll keep an eye out for it

**Comment by Spartan322** [comment]
This is related to godotengine/godot#97832
