### ISSUE TITLE
File system buggy behavior after creating a sub-forlder

### ISSUE THREAD

**Issue by Kiaazad** [Redot-Engine/redot-engine#728]
### Tested versions

After making a new sub-folder it will show it inside a `res://` folder for a while, it will update eventually, or goes away after expanding it.
![image](https://github.com/user-attachments/assets/792c6138-9396-4799-aa31-8bb98bc590c7)

Trying to delete it will remove the parent folder as well.

### System information

Redot v4.4.dev (5e7e5fc60) - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.2756) - AMD Ryzen 7 3800X 8-Core Processor (16 threads)

### Issue description

After making a new sub-folder it will show it inside a `res://` folder for a while, it will update eventually, or goes away after expanding it.

### Steps to reproduce

create a sub-folder

### Minimal reproduction project (MRP)

N/A

**Comment by SkogiB** [comment]
This is a known issue with Godot's 4.4dev build at the moment, not caused by us. It's pretty much just a waiting game for them to fix it. Thanks for putting in the effort to notify us though, we do appreciate it!

**Comment by Spartan322** [comment]
Its also solved on master already.
