### ISSUE TITLE
Why inconsistent font usage in logos?

### ISSUE THREAD

**Issue by MinePossu** [Redot-Engine/redot-engine#757]
### Tested versions

master

### System information

repo

### Issue description

https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.svg
https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.png

https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.svg
https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.png

which one is correct which one is wrong?

### Steps to reproduce

compare these
https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.svg
https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.png

https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.svg
https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.png

### Minimal reproduction project (MRP)

N/A

**Comment by AwesomeParley** [comment]
**Here's the images previewed so it's easier to see:**

https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.svg 
![image](https://raw.githubusercontent.com/Redot-Engine/redot-engine/edb8e2b1b2b09236bdcd76cb6c8b40b6fbb2abaf/logo_outlined.svg) (This Logo doesn't have an outline color, so in amoled dark mode the text is unable to be seen)

https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.png
![image](https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.png?raw=true)

https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.svg
![image](https://raw.githubusercontent.com/Redot-Engine/redot-engine/4f67c65d22b5d74f68ef6440c0fe99f206409613/logo_outlined.svg) (This Logo doesn't have an outline color, so in amoled dark mode the text is unable to be seen)

https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.png
![image](https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.png?raw=true)
