### ISSUE TITLE
Redot engine website needs to add additional paths to fix documentation links

### ISSUE THREAD

**Issue by tokengamedev** [Redot-Engine/redot-engine#767]
### Tested versions

redoteengine.org

### System information

Windows 11

### Issue description

Following links are missing
https://redotengine.org/license (\about\faq.rst, about/complying_with_licenses.rst)
https://redotengine.org/community (\introduction\community.rst)
https://redotengine.org/contact (\about\faq.rst)

### Steps to reproduce

Either pages have to be created to cater the needs of documentation or documentation has to be updated

### Minimal reproduction project (MRP)

N.A

**Comment by Spartan322** [comment]
Why was this submitted to the engine?

**Comment by tokengamedev** [comment]
Migrated the issue to right repo
