### ISSUE TITLE
[4.3] Viewport Texture Must Be Set To Use It

### ISSUE THREAD

**Issue by David-Everlasting-Media** [Redot-Engine/redot-engine#827]
### Tested versions

Reproducible in 4.3.beta.1.mono. 

### System information

Windows 11 (other users report some versions of Linux as well)

### Issue description

Sprite3D loses SubViewport texture assignment at runtime, even though it is correctly set. 
False error.

PR has been merged to Godot master branch already: https://github.com/godotengine/godot/pull/97029

### Steps to reproduce

In *most* cases game must be run before the assignment error appears.

New or existing Redot project, attempt to make 3D UI via the following steps: 
Add Sprite3D to Scene (or prefab scene) 
Add SubViewport as child of Sprite3D (or above it) 
Add UI Elements and scale. 
Assign Subviewport texture to Sprite3D
Run the game. 

The error may not be immediately apparent. 
Create an animation to fade the modulation of the Sprite3D at runtime, or change size. Changing the size of the subviewport triggers it in the editor before runtime, sometimes.
Run the game.

### Minimal reproduction project (MRP)

[broken-viewport-texture-assignment-MRP.zip](https://github.com/user-attachments/files/17579953/broken-viewport-texture-assignment-MRP.zip)

**Comment by Spartan322** [comment]
Fixed by #828

**Comment by David-Everlasting-Media** [comment]
Hi guys, sorry for necro, just confirming I've tested 4.3.beta.3.mono and the fix for this is working. Thanks fam. <3
