### ISSUE TITLE
Saving .gd files does not truncate whitespace at EOL

### ISSUE THREAD

**Issue by stevekonrad** [Redot-Engine/redot-engine#845]
### Tested versions

- 4.3-beta-3

### System information

Windows 10

### Issue description

Saving any .gd file does not truncate empty lines if they only consist of whitespace (or whitespace at the end of a line).

### Steps to reproduce

Open a .gd script (or create a new one).

1. empty line: 
   - just add some tabs
   - save the file
   - tabs remain in that line
2. line with code:
   - add some tabs at end of line (behind code)
   - save the file
   - tasb remain at end of line

### Minimal reproduction project (MRP)

Just any project with any .gd file really.

EDIT: seems to be affecting project that started in godot. more inconsistency mentioned in comment https://github.com/Redot-Engine/redot-engine/issues/845#issuecomment-2460915093.

**Comment by stevekonrad** [comment]
This seems to be fixed once you changed the setting in the editor-settings (text editor -> behaviour -> trim trailing whitespace on save).

I have yet to test, why the behaviour is initially different between godot and redot.

**Comment by stevekonrad** [comment]
without changing anything in the editor-settings (redot opened the project first, then godot did)
redot trims, godot does not
![image](https://github.com/user-attachments/assets/6501924f-d4a3-4b81-8e7d-449e3955b1fc)

there is something wrong with this setting for whatever reason... not sure i can make any sense of this behaviour anymore...

feel free to close as changing the setting once, immediately fixes the problem for any future edit (for the project in question at least).

**Comment by stevekonrad** [comment]
exact steps to repro the inconsistency (on my end)
versions:
- godot: `v4.3.stable.steam [77dcf97d8]`
- redot: `v4.3.beta.3.official [9bbd8033b]`

steps:
- create fresh project in redot
- create new file (e.g. `test.gd`)
- edit file by adding new tabs after `extends Node`
- save -> tabs trimmed
- open in godot
- edit file by adding new tabs after `extends Node`
- save -> tabs remain
- switch to redot (force-reload changes from godot)
- tabs are there -> save -> tabs gone

**Comment by Spartan322** [comment]
> feel free to close as changing the setting once, immediately fixes the problem for any future edit (for the project in question at least).

This is an editor setting, not a project setting, we did not change anything about editor settings, so it shouldn't be anything we've done.
