### ISSUE TITLE
Placeholder author "Godette" in Create/Edit Plugin page

### ISSUE THREAD

**Issue by Efra-EMX** [Redot-Engine/redot-engine#857]
### Tested versions

v4.3.rc.2.official [afc82bc08]

### System information

Redot v4.3.rc.2 - Windows 10.0.19045 - GLES3 (Compatibility) - Intel(R) Iris(R) Xe Graphics (Intel Corporation; 30.0.101.1960) - 12th Gen Intel(R) Core(TM) i5-1240P (16 Threads)

### Issue description

When creating / editing a plugin, if the `Author` field is empty, it will display "Godette" as a placeholder. We might want to rebrand it to "Redot-chan" or something.
![image](https://github.com/user-attachments/assets/0b1fc52f-8a8a-4377-b313-76f128c6fe2f)

### Steps to reproduce

1. Go to `Project > Project Settings > Plugins > Create New Plugin`.
2. See that the `Author` is displaying "Godette" as its placeholder.

### Minimal reproduction project (MRP)

N/A

**Comment by Efra-EMX** [comment]
On a slightly related note, there might be other mentions of "Godette" somewhere else in the engine too.

**Comment by trashguy** [comment]
``` ✘ trashguy@Nyx  /media/trashguy/FastDev/redot-engine   4.3  grep -rl "Godette" .  
./bin/redot.linuxbsd.editor.dev.x86_64
./bin/redot.linuxbsd.editor.x86_64
./platform/web/api/web_tools_editor_plugin.cpp
./doc/translations/zh_CN.po
./doc/translations/ga.po
./doc/classes/HTTPRequest.xml
./modules/libmodule_gltf.linuxbsd.editor.x86_64.a
./modules/libmodule_gltf.linuxbsd.editor.dev.x86_64.a
./modules/gltf/editor/editor_scene_exporter_gltf_settings.linuxbsd.editor.x86_64.o
./modules/gltf/editor/editor_scene_exporter_gltf_settings.cpp
./modules/gltf/editor/editor_scene_exporter_gltf_settings.linuxbsd.editor.dev.x86_64.o
./editor/libeditor.linuxbsd.editor.x86_64.a
./editor/libeditor.linuxbsd.editor.dev.x86_64.a
./editor/plugins/plugin_config_dialog.linuxbsd.editor.dev.x86_64.o
./editor/plugins/plugin_config_dialog.linuxbsd.editor.x86_64.o
./editor/plugins/plugin_config_dialog.cpp
```

**Comment by trashguy** [comment]
Changes added to #858
