### ISSUE TITLE
[4.3] Redot crashes when you right-click on Color() inside a script

### ISSUE THREAD

**Issue by iKuroiDev** [Redot-Engine/redot-engine#861]
### Tested versions

Redot 4.3 Release Candidate 2
Redot 4.3 Beta 2

### System information

Windows 11

### Issue description

Redot crashes when you right click a Color() inside a script. It works correctly if there's already a value inside Color(), but it crashes when it's empty

Expected behaviour:
Right clicking Color should open an option menu

### Steps to reproduce

`$Sprite2D.modulate = Color()`

- Right click the Color
- Redot crashes

`$Sprite2D.modulate = Color("FF0000")`
This one doesn't crash Redot

### Minimal reproduction project (MRP)

N/A

**Comment by Spartan322** [comment]
Confirmed able to replicate on 4.3-rc.3.

**Comment by Spartan322** [comment]
Closed by #866
