### ISSUE TITLE
Stop making people uncomfortable

### ISSUE THREAD

**Issue by At0mlix** [Redot-Engine/redot-engine#870]
### Tested versions

You hurt the ones who contribute.

### System information

You hurt the ones who contribute.

### Issue description

You hurt the ones who contribute.

### Steps to reproduce

You hurt the ones who contribute.

### Minimal reproduction project (MRP)

You hurt the ones who contribute.

**Comment by rmsilva1973** [comment]
Go back to under your bridge, troll. You're not welcome here.
