### ISSUE TITLE
Android build has issues. Can't install on any device. 

### ISSUE THREAD

**Issue by RakibRyan** [Redot-Engine/redot-engine#881]
### Tested versions

.

### System information

Android 

### Issue description

![Screenshot_2024-11-26-05-16-43-102_com google android packageinstaller-edit](https://github.com/user-attachments/assets/0ecd8b31-df51-40c0-b85e-876bf9f23de9)

### Steps to reproduce

.

### Minimal reproduction project (MRP)

N/A

**Comment by mjack3k** [comment]
Can confirm, same happens to me.

Tried with 4.3 apk. 

Device I tested with:
Xiaomi x5 pro 5g, android 14.

**Comment by mjack3k** [comment]
Can confirm, same happens to me.

Tried with 4.3 apk. 

Device I tested with:
Xiaomi x5 pro 5g, android 14.

**Comment by tindrew** [comment]
We have the android version(signed) being tested on the play store. We could use more testers, if you want shoot me an email at redotengine@gmail.com and I'll add you. Thanks!

**Comment by seacat17** [comment]
Confirmed on Galaxy M23 5G, Android 13, OneUI 5.1

**Comment by tindrew** [comment]
As I commented above, we have a build in testing on Google play. This build isn't signed and so won't install. Message redotengine@gmail.com if you'd like access. Thanks!
