### ISSUE TITLE
Make Redot Less Cringe

### ISSUE THREAD

**Issue by ghost** [Redot-Engine/redot-engine#895]
### Tested versions

- Linux Build

### System information

Arch Linux, latest version

### Issue description

Currently having some issues with the repo where I cringe whenever I go ahead and actually use it.

### Steps to reproduce

- Clone Redot repo
- Build from source as listed per documentation
- Open Redot

### Minimal reproduction project (MRP)

N/A

**Comment by FireBrandMint** [comment]
I too cringe, but only when i go to issues and see there's another troll post.
